variables:
  repository: 'jannemattila/webapp-azure-openai-demo-chat'

trigger:
  branches:
    include:
    - main
    - develop
  paths:
    include:
    - src/WebApp

name: 1.0.$(Rev:r)
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repository)
        command: 'buildAndPush'
        Dockerfile: "src/WebApp/Dockerfile"
        buildContext:
        tags: |
          $(Build.BuildNumber)
          latest
